blank_issues_enabled: false
contact_links:
  - name: Documentation
    url: https://github.com/robeckk/TinyUrl#readme
    about: Learn how to use TinyUrl
  - name: Discussions
    url: https://github.com/robeckk/TinyUrl/discussions
    about: Ask questions and share ideas with the community
